### ISSUE TITLE
Ratte module completely unfunctional

### ISSUE THREAD

**Issue by Bry-fi** [trustedsec/social-engineer-toolkit#218] opened 2016-04-08 03:34 UTC
The ratte module is printing errors such as
ratte_module not defined. For the java applet attack.

**Comment by trustedsec** [comment] 2016-04-18 13:45
What version of SET are you using? I am unable to reproduce:

[-] Launching the Remote Administration Tool Tommy Edition (RATTE) Payload...
Welcome to RATTE
RATTE is published for education only!
Use only with written permission of target!
For more technical information and parts of source code
check out chapter "B.2 Entwicklung eines Sicherheitspruefprogrammes"
of "Die Kunst der digitalen Verteidigung"
-> http://www.cul.de/verteidigung.html
RATTE Server Menue
1) list clients
2) activate client
3) remove client
4) remove all clients
5) remove&delete Client
99) stop Server
Choose:

**Comment by Bry-fi** [comment] 2016-04-20 01:35
7.0.3 and 7.0.6 this has been happening to all clean installs of setoolkit and I tried everything from direct source from github to kali repos. Same error and I have run the setup in the folder and everything from the downloaded git. Nothing's changed.

**Comment by trustedsec** [comment] 2016-04-20 01:52
Yeah - not much I can do if I can't reproduce, I follow the same steps in a vanilla Kali fully updated with the latest version or on Ubuntu 14.04 and Ratte loads fine. If I can't reproduce, I can't issue a fix - unless you can provide more detail, I'll need to close this issue.

**Comment by trustedsec** [comment] 2016-04-20 01:57
BTW code for this is located under src/webattack/java_applet - feel free to take a peek and debug.

**Closed** 2016-04-20 02:42 UTC
