### ISSUE TITLE
Python OpenSSL wasn't detected, note that SSL compatibility is now turned off

### ISSUE THREAD

**Issue by darkcyber** [trustedsec/social-engineer-toolkit#407] opened 2017-05-07 11:40 UTC
**Expected Behaviour**

It's should no error.

**Actual Behaviour**

Python OpenSSL wasn't detected, note that SSL compatibility is now turned off
Something went wrong, printing the error: zipimporter() argument 1 must be string, not function
affect in IP for post back set to localhost even set to 192.x.x.x

**Set Version**

7.6.2

**Similar Issue**
https://github.com/trustedsec/social-engineer-toolkit/issues/289

**How to fix**
Comment this line in `/usr/share/setoolkit/src/webattack/harvester/harvester.py`

```
# detect openssl module
#try:
#   from OpenSSL import SSL
#    from OpenSSL import SSL

# handle import error that openssl is not there
#except Exception as err:
#    print("Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.")
#    print_status("Printing error: " + str(err))
#    pass

```

Deepin 15.4

Is this some kind of bug?

Thanks in advance.

**Comment by Vinnyz** [comment] 2017-05-09 06:03
This solution is ok for me

**Comment by trustedsec** [comment] 2017-05-15 02:25
Fixed in version 2.7.3 - this is just a warning - not a bug.

**Closed by trustedsec** 2017-05-15 02:25 UTC

**Comment by pitoparry** [comment] 2017-05-27 04:59
please help am getting this error trying to clone a website

Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.
[*] Printing error: zipimporter() argument 1 must be string, not function

**Comment by BASS2** [comment] 2017-07-04 15:49
in what line you need to put that in theharverster.py

**Comment by darkcyber** [comment] 2017-07-05 01:59
@BASS2 find `detect openssl module` which contain like above tutorial

**Comment by pepitoigrillo** [comment] 2017-08-02 09:15
thank you so much, it help me a lot and fix the problem.

**Comment by unseenGhost** [comment] 2017-08-15 09:32
Thanks.   Work for me.  Fixed

**Comment by ozozozozoz** [comment] 2017-08-26 08:46
There is no harvester.py in my directory. Help!

**Comment by unseenGhost** [comment] 2017-08-26 17:47
Search well @ozozozozoz

**Comment by benseshi** [comment] 2017-09-10 05:34
*] Cloning the website: https://login.facebook.com/login.php
[*] This could take a little bit...
Python OpenSSL wasn't detected or PEM file not found, note that SSL compatibility will be affected.
[*] Printing error: zipimporter() argument 1 must be string, not function

The best way to use this attack is if username and password form
fields are available. Regardless, this captures all POSTs on a website.
[*] The Social-Engineer Toolkit Credential Harvester Attack
[*] Credential Harvester is running on port 80
[*] Information will be displayed to you as it arrives below:
"can any one help me please" im trying to clone a website im getting this

**Comment by dhamo003** [comment] 2017-10-02 11:42
same problem for me *benseshi*  anyone had a solution

**Comment by dhamo003** [comment] 2017-10-02 11:43
anyone is there??
